name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.19

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run vet
      run: |
        go vet .

    - name: Test
      run: go test -v ./...

  static-checks:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Install and run static-check
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.2"

    - name: Scan for Vulnerabilities in Code
      uses: Templum/govulncheck-action@v0.0.9
      with:
        fail-on-vuln: false
